version: '2'
services:
  # --------------------------------------------------------------------------------
  # DB Server
  # --------------------------------------------------------------------------------
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  # --------------------------------------------------------------------------------
  # Web Server
  # --------------------------------------------------------------------------------
  back:
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    ports:
      - 80:80
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0' -e development"
    volumes:
      - bundle_install:/usr/local/bundle
      - ./back:/app
      # exclude volumes
      - /app/.git
      - /app/.github
      - /app/.idea
      - /app/log
      - /app/tmp
      - /app/vendor
    links:
      - db:mysql
    tty: true
    environment:
      TZ: Asia/Tokyo

volumes:
  mysql-data:
    driver: local
  bundle_install:

